# Generated by Django 4.1.3 on 2022-12-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tag_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
    ]
